version: 2.1

jobs:
  build_push:
    docker:
      - image: docker:20.10.9-alpine3.14
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build
          command: ./scripts/build-image.sh
      - run:
          name: Push
          command: ./scripts/push-image.sh

workflows:
  build_push:
    jobs:
      - build_push:
          filters:
            branches:
              only: main
